// Mock pipeline results — used when backend is unavailable or for instant demo
export const MOCK_PROTEIN = {
  id: '4OLI',
  name: 'BRD4 Bromodomain',
  residue_count: 439,
  lysine_count: 31,
  pdb_data: null, // populated by backend
}

export const MOCK_CANDIDATES = [
  {
    id: 'APT-001',
    rank: 1,
    sequence: 'GCGCAUGGAUGCGUAGCUCAGUGGUAGAGCGCUUGCCUAAGCAAGGGUCGGCGGUUCGAGCCCGCCAUGCGC',
    dot_bracket: '((((((((....))))))))..((((((....)))))).((((.....)))).................',
    mfe: -24.7,
    scores: {
      fold_stability: 0.89,
      binding_score: 0.82,
      epitope_quality: 0.76,
      lysine_accessibility: 0.84,
      ternary_feasibility: 0.91,
      hook_penalty: 0.18,
    },
    degradability: 0.84,
    verdict: 'Excellent ternary geometry and E3 approach angle — top-tier degrader candidate.',
    hook_risk: false,
    e3_inhibitory: false,
    ternary_failure: false,
    steric_clash: false,
    contact_residues: 14,
    accessible_lysines: 8,
    kd_estimate: '2.3 nM',
    source: 'database',
    generation_basis: 'database seed // experimental aptamer scaffold',
    linker_recommendation: 'LINKER: PEG-8 (27.4 Å bridging distance)',
    linker_angstroms: 27.4,
    peg_units: 8,
  },
  {
    id: 'APT-002',
    rank: 2,
    sequence: 'GGGAGACAAGAAUAAACGCUCAAGGCUAGCGCGUAAACGUAGCGCUAGCUAGCUAGCUAGCGCGU',
    dot_bracket: '((((((....))))))..((((....))))..((((.....)))).................',
    mfe: -18.3,
    scores: {
      fold_stability: 0.74,
      binding_score: 0.79,
      epitope_quality: 0.71,
      lysine_accessibility: 0.68,
      ternary_feasibility: 0.78,
      hook_penalty: 0.31,
    },
    degradability: 0.74,
    verdict: 'Good ternary feasibility with adequate lysine exposure — viable PROTAC arm.',
    hook_risk: false,
    e3_inhibitory: false,
    ternary_failure: false,
    steric_clash: false,
    contact_residues: 11,
    accessible_lysines: 6,
    kd_estimate: '4.1 nM',
    source: 'generated',
    generation_basis: 'pocket charge POSITIVE // hydrophobic pocket // volume 312Å³ // stem-loop scaffold // loop 20nt',
    linker_recommendation: 'LINKER: PEG-11 (37.1 Å bridging distance)',
    linker_angstroms: 37.1,
    peg_units: 11,
  },
  {
    id: 'APT-003',
    rank: 3,
    sequence: 'CUAGGCCAGAUGGGCAGAGCAUGUAGCGUAGCGUAGCGUAGCGUAGCGCGUAGCGUAGCGUAG',
    dot_bracket: '((((....))))..((((((....))))))..((((....))))...................',
    mfe: -16.9,
    scores: {
      fold_stability: 0.71,
      binding_score: 0.65,
      epitope_quality: 0.83,
      lysine_accessibility: 0.59,
      ternary_feasibility: 0.63,
      hook_penalty: 0.44,
    },
    degradability: 0.67,
    verdict: 'Outstanding epitope geometry offset by moderate hook risk — linker optimisation advised.',
    hook_risk: false,
    e3_inhibitory: false,
    ternary_failure: false,
    steric_clash: false,
    contact_residues: 9,
    accessible_lysines: 4,
    kd_estimate: '8.7 nM',
    source: 'generated',
    generation_basis: 'pocket charge POSITIVE // polar pocket // volume 218Å³ // stem-loop scaffold // loop 14nt',
    linker_recommendation: 'LINKER: PEG-13 (44.8 Å bridging distance)',
    linker_angstroms: 44.8,
    peg_units: 13,
  },
  {
    id: 'APT-004',
    rank: 4,
    sequence: 'GAUCGAUGCGUAGCUAGCUAGCUAGCUAGCGUAGCGUAGCGUAGCGUAGCGUAGCGUAGCGU',
    dot_bracket: '(((....)))..((((....))))..((((....))))..((((.....)))).........',
    mfe: -13.2,
    scores: {
      fold_stability: 0.62,
      binding_score: 0.71,
      epitope_quality: 0.44,
      lysine_accessibility: 0.72,
      ternary_feasibility: 0.51,
      hook_penalty: 0.67,
    },
    degradability: 0.56,
    verdict: 'Strong binder but high hook effect risk — arm affinities mismatched by nearly 3 orders of magnitude.',
    hook_risk: true,
    e3_inhibitory: false,
    ternary_failure: false,
    steric_clash: false,
    contact_residues: 8,
    accessible_lysines: 7,
    kd_estimate: '18.4 nM',
    source: 'generated',
    generation_basis: 'pocket charge NEUTRAL // polar pocket // volume 175Å³ // stem-loop scaffold // loop 11nt',
    linker_recommendation: 'LINKER: PEG-15 (51.2 Å bridging distance)',
    linker_angstroms: 51.2,
    peg_units: 15,
  },
  {
    id: 'APT-005',
    rank: 5,
    sequence: 'CGAUCGAUGCGUAGCUAGCUAGCUAGCUAGCGUAGCGUAGCGUAGCGUAGCGUAGCGUAG',
    dot_bracket: '((((....))))..((((....))))..(((....)))..((((....))))..........',
    mfe: -11.8,
    scores: {
      fold_stability: 0.55,
      binding_score: 0.58,
      epitope_quality: 0.61,
      lysine_accessibility: 0.63,
      ternary_feasibility: 0.22,
      hook_penalty: 0.29,
    },
    degradability: 0.52,
    verdict: 'Ternary complex unfeasible — 97.6 Å bridging distance exceeds PEG linker range. Re-design linker attachment point.',
    hook_risk: false,
    e3_inhibitory: false,
    ternary_failure: true,
    steric_clash: false,
    contact_residues: 7,
    accessible_lysines: 5,
    kd_estimate: '31.2 nM',
    source: 'generated',
    generation_basis: 'pocket charge NEGATIVE // polar pocket // volume 175Å³ // stem-loop scaffold // loop 11nt',
    linker_recommendation: 'LINKER: PEG-34 (97.6 Å bridging distance)',
    linker_angstroms: 97.6,
    peg_units: 34,
  },
]

export const MOCK_SUMMARY = {
  generated: 247,
  stable_folds: 71,
  docked: 25,
  ranked: 5,
  elapsed_s: 47,
}

export const PIPELINE_STEPS = [
  { id: 1,  key: 'fetch_structure',   label: 'Fetch Structure' },
  { id: 2,  key: 'identify_sites',    label: 'Identify Sites' },
  { id: 3,  key: 'generate_library',  label: 'Gen Library' },
  { id: 4,  key: 'fold_filter',       label: 'Fold Filter' },
  { id: 5,  key: 'predict_3d',        label: '3D Prediction' },
  { id: 6,  key: 'docking',           label: 'Docking' },
  { id: 7,  key: 'epitope_score',     label: 'Epitope Score' },
  { id: 8,  key: 'lysine_score',      label: 'Lysine Score' },
  { id: 9,  key: 'ternary_model',     label: 'Ternary Model' },
  { id: 10, key: 'hook_penalty',      label: 'Hook Penalty' },
]

export const STEP_DESCRIPTIONS = {
  fetch_structure:   'Fetching protein structure from RCSB PDB and parsing 3D coordinates...',
  identify_sites:    'Running fpocket to identify druggable surface pockets — extracting volume, druggability, and charge class...',
  generate_library:  'Generating pocket-property-biased RNA sequences using stem-loop scaffold (loop length driven by pocket volume)...',
  fold_filter:       'Filtering candidates by fold stability via ViennaRNA RNAfold (MFE threshold: −5.0 kcal/mol)...',
  predict_3d:        'Predicting 3D aptamer structures for top 25 candidates via rna-tools...',
  docking:           'Running rDock protein–RNA docking constrained to top binding pocket (HADDOCK fallback)...',
  epitope_score:     'Computing E3 approach geometry and checking for CRBN inhibitory contacts via BioPython SASA...',
  lysine_score:      'Scoring surface-exposed lysine accessibility on E3-facing hemisphere...',
  ternary_model:     'Modelling ternary complex geometry using CRBN-pomalidomide reference (PDB 4CI1) — estimating PEG linker length and steric clash...',
  hook_penalty:      'Calculating hook effect penalty from arm affinity asymmetry (Kd2 = 5 nM, pomalidomide–CRBN)...',
}
